"""baseline schema

Revision ID: b926dcfba22b
Revises: 
Create Date: 2026-07-07 20:36:21.717728
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b926dcfba22b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('patients',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('patient_number', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('gender', sa.Enum('MAENNLICH', 'WEIBLICH', 'DIVERS', name='gender'), nullable=False),
    sa.Column('insurance_type', sa.Enum('GKV', 'PKV', 'SELBSTZAHLER', 'BG', name='insurancetype'), nullable=False),
    sa.Column('insurance_id', sa.String(length=50), nullable=True),
    sa.Column('insurance_company', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'patient_number', name='uq_patient_tenant_number')
    )
    op.create_index('ix_patient_tenant', 'patients', ['tenant_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'ARZT', 'MFA', 'READONLY', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('totp_secret', sa.String(length=64), nullable=True),
    sa.Column('totp_enabled', sa.Boolean(), nullable=False),
    sa.Column('totp_backup_codes', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'email', name='uq_user_tenant_email')
    )
    op.create_table('api_keys',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('key_prefix', sa.String(length=20), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('created_by_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    op.create_index('ix_apikey_hash', 'api_keys', ['key_hash'], unique=False)
    op.create_index('ix_apikey_tenant', 'api_keys', ['tenant_id'], unique=False)
    op.create_table('case_files',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('created_by_id', sa.String(length=36), nullable=False),
    sa.Column('treatment_date', sa.Date(), nullable=False),
    sa.Column('report_text', sa.Text(), nullable=False),
    sa.Column('report_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('OFFEN', 'IN_BEARBEITUNG', 'ABGESCHLOSSEN', 'ARCHIVIERT', name='casestatus'), nullable=False),
    sa.Column('quartal', sa.String(length=6), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_casefile_quartal', 'case_files', ['tenant_id', 'quartal'], unique=False)
    op.create_index('ix_casefile_tenant_patient', 'case_files', ['tenant_id', 'patient_id'], unique=False)
    op.create_table('system_settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('gop_suggestions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_file_id', sa.String(length=36), nullable=False),
    sa.Column('gop_code', sa.String(length=10), nullable=False),
    sa.Column('gop_description', sa.Text(), nullable=True),
    sa.Column('start_char', sa.Integer(), nullable=True),
    sa.Column('end_char', sa.Integer(), nullable=True),
    sa.Column('source_text', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('color_hex', sa.String(length=7), nullable=False),
    sa.Column('status', sa.Enum('VORGESCHLAGEN', 'AKZEPTIERT', 'ABGELEHNT', name='gopstatus'), nullable=False),
    sa.Column('mcp_validated', sa.Boolean(), nullable=False),
    sa.Column('mcp_exclusion_flags', sa.JSON(), nullable=True),
    sa.Column('llm_reasoning', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_file_id'], ['case_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_gop_case_file', 'gop_suggestions', ['case_file_id'], unique=False)
    op.create_index('ix_gop_code_case', 'gop_suggestions', ['gop_code', 'case_file_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('case_file_id', sa.String(length=36), nullable=True),
    sa.Column('gop_suggestion_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.Enum('GOP_AKZEPTIERT', 'GOP_ABGELEHNT', 'GOP_VORGESCHLAGEN', 'FALLAKTE_ERSTELLT', 'FALLAKTE_ABGESCHLOSSEN', 'ANALYSE_GESTARTET', name='auditaction'), nullable=False),
    sa.Column('gop_code', sa.String(length=10), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('log_metadata', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_file_id'], ['case_files.id'], ),
    sa.ForeignKeyConstraint(['gop_suggestion_id'], ['gop_suggestions.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_case_file', 'audit_logs', ['case_file_id'], unique=False)
    op.create_index('ix_audit_tenant_created', 'audit_logs', ['tenant_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_audit_tenant_created', table_name='audit_logs')
    op.drop_index('ix_audit_case_file', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_gop_code_case', table_name='gop_suggestions')
    op.drop_index('ix_gop_case_file', table_name='gop_suggestions')
    op.drop_table('gop_suggestions')
    op.drop_table('system_settings')
    op.drop_index('ix_casefile_tenant_patient', table_name='case_files')
    op.drop_index('ix_casefile_quartal', table_name='case_files')
    op.drop_table('case_files')
    op.drop_index('ix_apikey_tenant', table_name='api_keys')
    op.drop_index('ix_apikey_hash', table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_table('users')
    op.drop_index('ix_patient_tenant', table_name='patients')
    op.drop_table('patients')
    op.drop_table('tenants')
    # ### end Alembic commands ###
