"""
EBM-Seed-Daten für Demo und Testing.
Repräsentative GOPs aus verschiedenen Kapiteln mit Ausschlüssen und Restriktionen.
Datenstand: EBM 2024 Q1 (vereinfacht).
"""
from datetime import date

VALID_FROM = "2024-01-01"

SEED_GOPS: list[dict] = [
    # ── Kapitel 1: Allgemeine GOP ────────────────────────────────────────
    {
        "code": "01100",
        "description": "Unvorhergesehene Inanspruchnahme des Vertragsarztes durch einen Patienten in dringenden Fällen außerhalb der Sprechstundenzeiten",
        "chapter": "1",
        "chapter_title": "Allgemeine Gebührenordnungspositionen",
        "time_value_minutes": 5,
        "value_points": 126.0,
        "insurance_types": ["GKV"],
        "exclusions": ["01101"],
        "valid_from": VALID_FROM,
    },
    {
        "code": "01101",
        "description": "Unvorhergesehene Inanspruchnahme des Vertragsarztes durch einen Patienten in dringenden Fällen an Samstagen, Sonn- und Feiertagen",
        "chapter": "1",
        "chapter_title": "Allgemeine Gebührenordnungspositionen",
        "time_value_minutes": 5,
        "value_points": 189.0,
        "insurance_types": ["GKV"],
        "exclusions": ["01100"],
        "valid_from": VALID_FROM,
    },
    {
        "code": "01435",
        "description": "Haus- oder fachärztliche Bereitschaftspauschale – Ordinationskomplex für die Versorgung eines Patienten",
        "chapter": "1",
        "chapter_title": "Allgemeine Gebührenordnungspositionen",
        "time_value_minutes": 10,
        "value_points": 165.0,
        "insurance_types": ["GKV"],
        "exclusions": [],
        "valid_from": VALID_FROM,
    },
    {
        "code": "01600",
        "description": "Ärztlicher Bericht nach Untersuchung eines Patienten",
        "chapter": "1",
        "chapter_title": "Allgemeine Gebührenordnungspositionen",
        "time_value_minutes": 5,
        "value_points": 55.0,
        "insurance_types": ["GKV"],
        "exclusions": ["01601"],
        "valid_from": VALID_FROM,
    },
    {
        "code": "01601",
        "description": "Individueller Arztbrief in freier Formulierung",
        "chapter": "1",
        "chapter_title": "Allgemeine Gebührenordnungspositionen",
        "time_value_minutes": 20,
        "value_points": 200.0,
        "insurance_types": ["GKV"],
        "exclusions": ["01600"],
        "valid_from": VALID_FROM,
    },
    # ── Kapitel 3: Allgemeinmedizin ──────────────────────────────────────
    {
        "code": "03000",
        "description": "Hausärztliche Grundpauschale – umfassende Beurteilung und Behandlung für Patienten ab 18 Jahren",
        "chapter": "3",
        "chapter_title": "Hausärztlicher Versorgungsbereich",
        "time_value_minutes": 15,
        "value_points": 213.0,
        "insurance_types": ["GKV"],
        "exclusions": ["03010"],
        "age_restriction_min": 18,
        "valid_from": VALID_FROM,
    },
    {
        "code": "03010",
        "description": "Hausärztliche Grundpauschale für Patienten ab 75 Jahren",
        "chapter": "3",
        "chapter_title": "Hausärztlicher Versorgungsbereich",
        "time_value_minutes": 20,
        "value_points": 258.0,
        "insurance_types": ["GKV"],
        "exclusions": ["03000"],
        "age_restriction_min": 75,
        "valid_from": VALID_FROM,
    },
    {
        "code": "03360",
        "description": "Geriatrisches Basisassessment, Ersterhebung",
        "chapter": "3",
        "chapter_title": "Hausärztlicher Versorgungsbereich",
        "time_value_minutes": 40,
        "value_points": 470.0,
        "insurance_types": ["GKV"],
        "exclusions": [],
        "age_restriction_min": 70,
        "valid_from": VALID_FROM,
    },
    # ── Kapitel 4: Kinder- und Jugendmedizin ────────────────────────────
    {
        "code": "04000",
        "description": "Pädiatrische Grundpauschale für Kinder und Jugendliche bis 17 Jahre",
        "chapter": "4",
        "chapter_title": "Kinder- und Jugendmedizin",
        "time_value_minutes": 15,
        "value_points": 230.0,
        "insurance_types": ["GKV"],
        "exclusions": [],
        "age_restriction_max": 17,
        "valid_from": VALID_FROM,
    },
    # ── Kapitel 13: Innere Medizin ────────────────────────────────────────
    {
        "code": "13210",
        "description": "Grundpauschale innere Medizin ohne Schwerpunktbezeichnung",
        "chapter": "13",
        "chapter_title": "Innere Medizin",
        "time_value_minutes": 20,
        "value_points": 217.0,
        "insurance_types": ["GKV"],
        "exclusions": [],
        "age_restriction_min": 18,
        "valid_from": VALID_FROM,
    },
    # ── EKG / Diagnostik ─────────────────────────────────────────────────
    {
        "code": "27321",
        "description": "Langzeit-EKG-Untersuchung – Aufzeichnung und Auswertung über mindestens 18 Stunden",
        "chapter": "27",
        "chapter_title": "Kardiologie",
        "time_value_minutes": 30,
        "value_points": 347.0,
        "insurance_types": ["GKV"],
        "exclusions": [],
        "valid_from": VALID_FROM,
    },
    {
        "code": "27310",
        "description": "EKG – Auswertung eines Elektrokardiogramms",
        "chapter": "27",
        "chapter_title": "Kardiologie",
        "time_value_minutes": 5,
        "value_points": 60.0,
        "insurance_types": ["GKV"],
        "exclusions": [],
        "valid_from": VALID_FROM,
    },
    # ── Beratung / Prävention ─────────────────────────────────────────────
    {
        "code": "01732",
        "description": "Gesundheitsuntersuchung (Check-up) für Versicherte ab 35 Jahren",
        "chapter": "1",
        "chapter_title": "Allgemeine Gebührenordnungspositionen",
        "time_value_minutes": 30,
        "value_points": 472.0,
        "insurance_types": ["GKV"],
        "exclusions": [],
        "age_restriction_min": 35,
        "valid_from": VALID_FROM,
    },
    {
        "code": "03230",
        "description": "Problemorientiertes ärztliches Gespräch, das aufgrund von Art, Schwere und Komplexität der Erkrankung erforderlich ist, Dauer mindestens 10 Minuten",
        "chapter": "3",
        "chapter_title": "Hausärztlicher Versorgungsbereich",
        "time_value_minutes": 10,
        "value_points": 128.0,
        "insurance_types": ["GKV"],
        "exclusions": [],
        "valid_from": VALID_FROM,
    },
    {
        "code": "01430",
        "description": "Verwaltungskomplex – Bearbeitung und Befundkommunikation schriftlicher Arztbriefe",
        "chapter": "1",
        "chapter_title": "Allgemeine Gebührenordnungspositionen",
        "time_value_minutes": 5,
        "value_points": 30.0,
        "insurance_types": ["GKV"],
        "exclusions": [],
        "valid_from": VALID_FROM,
    },

    # ── Kapitel 13: Kardiologische GOP ──────────────────────────────────
    {
        "code": "13250",
        "description": "Elektrokardiographische Untersuchung (Ruhe-EKG), einschließlich Auswertung und Beurteilung, mindestens 12 Ableitungen",
        "chapter": "13",
        "chapter_title": "Innere Medizin / Kardiologie",
        "time_value_minutes": 10,
        "value_points": 60.0,
        "insurance_types": ["GKV"],
        "exclusions": [],
        "valid_from": VALID_FROM,
    },
    {
        "code": "13251",
        "description": "Belastungs-EKG (Ergometrie), Aufzeichnung und Auswertung eines Belastungs-EKG, Überwachung während der Belastungsphase und Nachbeobachtungsphase",
        "chapter": "13",
        "chapter_title": "Innere Medizin / Kardiologie",
        "time_value_minutes": 30,
        "value_points": 244.0,
        "insurance_types": ["GKV"],
        "exclusions": [],
        "valid_from": VALID_FROM,
    },
    {
        "code": "13254",
        "description": "Langzeit-EKG-Untersuchung über mindestens 18 Stunden",
        "chapter": "13",
        "chapter_title": "Innere Medizin / Kardiologie",
        "time_value_minutes": 20,
        "value_points": 172.0,
        "insurance_types": ["GKV"],
        "exclusions": ["13250"],
        "valid_from": VALID_FROM,
    },
    {
        "code": "13300",
        "description": "Blutdruckmessung: 24-Stunden-Langzeit-Blutdruckmessung",
        "chapter": "13",
        "chapter_title": "Innere Medizin / Kardiologie",
        "time_value_minutes": 10,
        "value_points": 68.0,
        "insurance_types": ["GKV"],
        "exclusions": [],
        "valid_from": VALID_FROM,
    },
    # ── Kapitel 33: Sonographie ──────────────────────────────────────────
    {
        "code": "33042",
        "description": "Sonographische Untersuchung des Abdomens und/oder des Retroperitonealraums, gegebenenfalls einschließlich der Nieren, Nebennieren und Harnblase",
        "chapter": "33",
        "chapter_title": "Ultraschalldiagnostik",
        "time_value_minutes": 15,
        "value_points": 116.0,
        "insurance_types": ["GKV"],
        "exclusions": [],
        "valid_from": VALID_FROM,
    },
    # ── Kapitel 3: Hausarzt / Beratung ──────────────────────────────────
    {
        "code": "03220",
        "description": "Zuschlag zur Versichertenpauschale nach der GOP 03000 für die Behandlung und Betreuung eines Patienten mit mindestens einer lebensverändernden chronischen Erkrankung",
        "chapter": "3",
        "chapter_title": "Hausärztlicher Versorgungsbereich",
        "time_value_minutes": 15,
        "value_points": 176.0,
        "insurance_types": ["GKV"],
        "exclusions": [],
        "valid_from": VALID_FROM,
    },
]
